import fs from 'fs/promises';
import path from 'path';
import { BaseGenerator } from './base.js';

export class TypesGenerator extends BaseGenerator {
  async generate(): Promise<void> {
    const content = this.generateContent();
    const outputPath = path.join(this.context.config.outputDir, 'types.ts');

    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, content, 'utf-8');
  }

  private generateContent(): string {
    return `// Auto-generated type definitions
// Do not edit this file manually

import type { z } from 'zod';

// Re-export endpoint configuration types
export type { APIConfig, APIEndpoint, HTTPMethod } from '@vietbus/api-codegen/config';

/**
 * Type helper to extract params schema from an endpoint
 */
export type ExtractParams<T> = T extends { params: infer P extends z.ZodType }
  ? z.infer<P>
  : never;

/**
 * Type helper to extract query schema from an endpoint
 */
export type ExtractQuery<T> = T extends { query: infer Q extends z.ZodType }
  ? z.infer<Q>
  : never;

/**
 * Type helper to extract body schema from an endpoint
 */
export type ExtractBody<T> = T extends { body: infer B extends z.ZodType }
  ? z.infer<B>
  : never;

/**
 * Type helper to extract response schema from an endpoint
 */
export type ExtractResponse<T> = T extends { response: infer R extends z.ZodType }
  ? z.infer<R>
  : never;

/**
 * Import your API config to get typed endpoints
 * 
 * @example
 * import { apiConfig } from './config/endpoints';
 * export type APIEndpoints = typeof apiConfig.endpoints;
 */
export type APIEndpoints = Record<string, any>;
`;
  }
}
